<?php

namespace App\Services;

use App\Models\Project;
use App\Models\ProjectVersion;
use ZipArchive;

class ZipExportService
{
    /**
     * Build a self-contained ZIP for the given project.
     * Returns the path to the temporary ZIP file.
     */
    public function export(Project $project): string
    {
        /** @var ProjectVersion|null $version */
        $version = $project->versions()->latest()->first();

        if (!$version) {
            throw new \RuntimeException('No versions found for this project.');
        }

        $htmlContent = $this->wrapHtml($version->content, $project->name);

        $tmpPath = tempnam(sys_get_temp_dir(), 'lyzard_export_') . '.zip';

        $zip = new ZipArchive();
        if ($zip->open($tmpPath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new \RuntimeException('Could not create ZIP archive.');
        }

        $zip->addFromString('index.html', $htmlContent);
        $zip->addFromString('README.md', $this->buildReadme($project));
        $zip->close();

        return $tmpPath;
    }

    /**
     * Ensure the HTML content is a full standalone page.
     * If it already has <!DOCTYPE html> we keep it as-is; otherwise we wrap it.
     */
    private function wrapHtml(string $content, string $projectName): string
    {
        $trimmed = ltrim($content);

        if (stripos($trimmed, '<!DOCTYPE') === 0 || stripos($trimmed, '<html') === 0) {
            return $content;
        }

        return <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{$projectName}</title>
  <meta name="generator" content="Lyzard.ai" />
</head>
<body>
{$content}
</body>
</html>
HTML;
    }

    private function buildReadme(object $project): string
    {
        $date = now()->toDateString();
        return <<<MD
# {$project->name}

Generated by **Lyzard.ai** on {$date}.

## Usage

Open `index.html` in any modern browser to preview your landing page.
All styles and scripts are self-contained within the HTML file.

---
*Powered by [Lyzard.ai](https://lyzard.ai)*
MD;
    }
}
